src/MangoPayInegration.Web/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MangoPayHttps.Api;
using MangoPay;
using MangoPay.SDK;
using MangoPay.SDK.Entities.POST;
using MangoPay.SDK.Core.Enumerations;
using System.Net;
using MangoPay.SDK.Entities.GET;
using MangoPay.SDK.Core;
using MangoPay.SDK.Entities;
using System.Text;
using System.Globalization;
using MangoPay.Db;
using NlogLogger;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace MangoPayInegration.Controllers
{
    public class ApiController : Controller
    {
        [HttpPost]
        public ActionResult CreateNaturalUser(string jsonData)
        {
            ViewModelUserNaturalDTO model =
                HtmlHelpers.GetObjectFromEncodedJson<ViewModelUserNaturalDTO>(jsonData, typeof(ViewModelUserNaturalDTO));

            UserNaturalPostDTO postUser = PostObjectsFactory.GetNaturalUserPostDTO(model);
            UserNaturalDTO createdUser = null;

            try
            {
                createdUser = MangoPayHttpsApi.CreateNaturalUser(postUser, AppSettingsHelper.GetSettings());
                LogDataController.SaveLogData(createdUser, RequestType.Request);
            }
            catch (ResponseException exc)
            {
                LogDataController.SaveLogData(exc, RequestType.Responce);
                return Json(new { Result = "Error", Description = string.Format("User creation failed. <br />{0}", HtmlHelpers.ParseMPResponceError(exc)) });
            }

            return Json(new { Result = "Ok", Description = string.Format("User successfuly created. User ID: {0}", createdUser.Id) });
        }
        [HttpPost]
        public ActionResult CreateLegalUser(string jsonData)
        {
            ViewModelUserLegallDTO model =
                HtmlHelpers.GetObjectFromEncodedJson<ViewModelUserLegallDTO>(jsonData, typeof(ViewModelUserLegallDTO));
            UserLegalPostDTO postUser = PostObjectsFactory.GetLegalUserPostDTO(model);
            UserLegalDTO createdUser = null;

            try
            {
                createdUser = MangoPayHttpsApi.CreateLegalUser(postUser, AppSettingsHelper.GetSettings());
                LogDataController.SaveLogData(createdUser, RequestType.Request);
            }
            catch (ResponseException exc)
            {
                LogDataController.SaveLogData(exc, RequestType.Responce);
                return Json(new { Result = "Error", Description = string.Format("User creation failed. <br />{0}", HtmlHelpers.ParseMPResponceError(exc)) });
            }

            return Json(new { Result = "Ok", Description = string.Format("User successfuly created. User ID: {0}", createdUser.Id) });
        }
        [HttpPost]
        public ActionResult CreateWallet(string jsonData)
        {
            ViewModelWalletDTO model =
                HtmlHelpers.GetObjectFromEncodedJson<ViewModelWalletDTO>(jsonData, typeof(ViewModelWalletDTO));
            WalletPostDTO postWallet = PostObjectsFactory.GetWalletPostDTO(model);

            WalletDTO createdWallet = null;
            try
            {
                createdWallet = MangoPayHttpsApi.CreateWallet(postWallet, AppSettingsHelper.GetSettings());
                LogDataController.SaveLogData(model, RequestType.Request);
            }
            catch (ResponseException exc)
            {
                LogDataController.SaveLogData(exc, RequestType.Responce);
                return Json(new { Result = "Error", Description = string.Format("Waller creation failed. <br />{0}", HtmlHelpers.ParseMPResponceError(exc)) });
            }

            return Json(new { Result = "Ok", Description = string.Format("Wallet successfuly created. Wallet ID: {0}", createdWallet.Id) });
        }
        [HttpPost]
        public ActionResult CreatePayIn(string jsonData)
        {
            Session["_payInState"] = null;
            PayInCardWebDTO createdPayin = null;
            try
            {
                ViewModelPayinDTO model = HtmlHelpers.GetObjectFromEncodedJson<ViewModelPayinDTO>(jsonData, typeof(ViewModelPayinDTO));
                PayInCardWebPostDTO postPayin = PostObjectsFactory.GetPayInCardWebDTO(model);

                LogDataController.SaveLogData(model, RequestType.Request);
                createdPayin = MangoPayHttpsApi.CreatePayIn(postPayin, AppSettingsHelper.GetSettings());
                LogDataController.SaveLogData(createdPayin, RequestType.Responce);
            }
            catch (ResponseException exc)
            {
                LogDataController.SaveLogData(exc, RequestType.Responce);
                return Json(new { Result = "Error", Description = string.Format("Payin submition failed. <br />{0}", HtmlHelpers.ParseMPResponceError(exc)) });
            }
            catch (Exception exc)
            {
                NlogHelper.LogError(exc);
                LogDataController.SaveLogData(exc, RequestType.Responce);
                return Json(new { Result = "Error", Description = string.Format("Payin submition failed. Error: {0}", exc.InnerException) });
            }

            if (createdPayin != null && createdPayin.Status == TransactionStatus.CREATED)
            {
                return Json(new { Result = "Ok", Description = "Payin in progress. Waiting for server to reply...", PayInUrl = createdPayin.RedirectURL });
            }
            else if (createdPayin != null && createdPayin.Status == TransactionStatus.FAILED)
            {
                return Json(new { Result = "Error", Description = createdPayin.ResultMessage });
            }

            return Json(new { Result = "Error", Description = "Internal server error. Error code: 500" });
        }
        public ActionResult PayInReturn(string transactionId)
        {
            Session["_payInState"] = true;
            return View("~/Views/Shared/Empty.cshtml");
        }
        [HttpPost]
        public ActionResult GetPayInState(string jsonData)
        {
            if (Session["_payInState"] != null && ((bool)Session["_payInState"]))
            {
                return Json(new { Result = "Succsess", Description = "Payin successfully created.", StopTimer = true });
            }

            return Json(new { InProgress = true });
        }
        public ActionResult CreateTransfer(string jsonData)
        {
            TransferDTO createdTransfer = null;
            try
            {
                ViewModelTransferDTO model = HtmlHelpers.GetObjectFromEncodedJson<ViewModelTransferDTO>(jsonData, typeof(ViewModelTransferDTO));
                TransferPostDTO postTransfer = PostObjectsFactory.GetTransferDTO(model);

                createdTransfer = MangoPayHttpsApi.CreateTransfer(postTransfer, AppSettingsHelper.GetSettings());
                LogDataController.SaveLogData(model, RequestType.Request);
            }
            catch (ResponseException exc)
            {
                LogDataController.SaveLogData(exc, RequestType.Responce);
                return Json(new { Result = "Error", Description = string.Format("Transfer creation failed. <br />{0}", HtmlHelpers.ParseMPResponceError(exc)) });
            }
            catch (Exception exc)
            {
                NlogHelper.LogError(exc);
                LogDataController.SaveLogData(exc, RequestType.Responce);
                return Json(new { Result = "Error", Description = string.Format("Transfer creation failed. Error: {0}", exc.InnerException) });
            }

            if (createdTransfer != null)
            {
                if (createdTransfer.Status == TransactionStatus.FAILED)
                {
                    return Json(new { Result = "Error", Description = createdTransfer.ResultMessage });
                }

                return Json(new { Result = "Ok", Description = "Transfer successfuly created." });
            }

            return Json(new { Response = "Error", Description = "Internal server error. Error code: 500" });
        }
        [HttpGet]
        public static List<UserDTO> GetAllMangoPayUsers()
        {
            return MangoPayHttpsApi.GetAllUsersDto(AppSettingsHelper.GetSettings());
        }
        [HttpPost]
        public ActionResult GetUserWallet(string userId)
        {
            List<WalletDTO> wallets = MangoPayHttpsApi.GetAllUserWalletsDto(userId, AppSettingsHelper.GetSettings());

            if (wallets != null && wallets.Count > 0)
            {
                return Json(new { Result = "Ok", WalletId = wallets.First().Id });
            }
            return Json(new { Result = "Ok", WalletId = "User does not have any wallets" });
        }
        [HttpPost]
        public ActionResult GetUserLegalPersonType(string userId)
        {
            if (!userId.Equals("-1"))
            {
                UserLegalDTO userLegal = MangoPayHttpsApi.GetLegalUserDto(userId, AppSettingsHelper.GetSettings());

                if (userLegal != null)
                {
                    return Json(new { Result = "Ok", PersonType = userLegal.LegalPersonType.ToString() });
                }
                return Json(new { Result = "Error", PersonType = LegalPersonType.NotSpecified.ToString() });
            }

            return Json(new { Result = "Ok" });
        }
        [HttpPost]
        public ActionResult SubmitDocuments(string jsonData)
        {
            try
            {
                ViewModelKYCDocumentsDTO model =
                HtmlHelpers.GetObjectFromEncodedJson<ViewModelKYCDocumentsDTO>(jsonData, typeof(ViewModelKYCDocumentsDTO));

                string errors = FilesHelper.ValidateUploadedDocuments(model);

                if (errors.Length == 0)
                {
                    List<KycDocumentTransferObject> post = PostObjectsFactory.GetDocumentsList(model);

                    MangoPayHttpsApi.CreateKYCDocuments(post, AppSettingsHelper.GetSettings());

src/MangoPayInegration.Web/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MangoPay;
using MangoPay.Db;
using MangoPay.SDK;

namespace MangoPayInegration.Controllers
{
    public class MainController : Controller
    {
        public ActionResult Index()
        {
           return View();
        }
        public ActionResult Users()
        {
            return View();
        }
        public ActionResult Wallets()
        {
            return View();
        }
        public ActionResult KYCDocuments()
        {
            return View();
        }
        public ActionResult Transfers()
        {
            return View();
        }
        public ActionResult PayIns()
        {
            return View();
        }

    }
}

src/MangoPayInegration.Web/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-sm-3">
        <div class="card mt-2">
            <div class="card-body card-bodyMH">
                <h3>Users</h3>
                <p>
                    User operations. 
                </p>
                @Html.ActionLink("Proceed...", "Users", "Main", new { area = "" }, new { @class = "btn btn-outline-secondary mt-1 float-right" })
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card mt-2">
            <div class="card-body card-bodyMH">
                <h3>Wallets</h3>
                <p>
                    Wallets operations.
                </p>
                @Html.ActionLink("Proceed...", "Wallets", "Main", new { area = "" }, new { @class = "btn btn-outline-secondary mt-1 float-right" })
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card mt-2">
            <div class="card-body card-bodyMH">
                <h3>PayIns</h3>
                <p>
                    PayIn operations.
                </p>
                @Html.ActionLink("Proceed...", "PayIns", "Main", new { area = "" }, new { @class = "btn btn-outline-secondary mt-1 float-right" })
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card mt-2">
            <div class="card-body card-bodyMH">
                <h3>KYC documents</h3>
                <p>
                    KYC documents operations. 
                </p>
                @Html.ActionLink("Proceed...", "KYCDocuments", "Main", new { area = "" }, new { @class = "btn btn-outline-secondary mt-1 float-right" })
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card mt-2">
            <div class="card-body card-bodyMH">
                <h3>Transfers</h3>
                <p>
                    Transfers operations. 
                </p>
                @Html.ActionLink("Proceed...", "Transfers", "Main", new { area = "" }, new { @class = "btn btn-outline-secondary mt-1 float-right" })
            </div>
        </div>
    </div>
</div>

src/MangoPayInegration.Web/Views/Main/KYCDocuments.cshtml
@using MangoPay.SDK.Entities.GET;
@using MangoPayInegration.Controllers;
@using MangoPay.SDK.Core.Enumerations;


@{
    ViewBag.Title = "KYC documents upload";
}

<div class="card mt-2 form-control">
    <div class="card-body">
        <div class="row" id="divUploadCtrls">
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link active" id="createDoc-tab" data-toggle="tab" href="#nav-create" role="tab" aria-controls="nav-create" aria-selected="true">Create KYC document</a>
                    <a class="nav-item nav-link" id="nav-view-tab" data-toggle="tab" href="#nav-view" role="tab" aria-controls="nav-view" aria-selected="false">View KYC documents</a>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-create" role="tabpanel" aria-labelledby="nav-create-tab">
                    @Html.Partial("~/Views/Main/KYCDocuments/CreateKYCDocuments.cshtml")
                </div>
                <div class="tab-pane fade" id="nav-view" role="tabpanel" aria-labelledby="nav-view-tab">
                    @Html.Partial("~/Views/Main/KYCDocuments/ViewKYCDocuments.cshtml")
                </div>
            </div>
        </div>
    </div>
</div>

src/MangoPayInegration.Web/Views/Main/PayIns.cshtml
@using MangoPay.SDK.Entities.GET;
@using MangoPayInegration.Controllers;
@using MangoPay.SDK.Core.Enumerations;

@{
    ViewBag.Title = "Create payIn";
}

@{
    List<UserDTO> users = ApiController.GetAllMangoPayUsers();

    <div class="row" id="divPayin">
        <div class="card mt-2 form-control">
            <div class="card-body">
                <h2>@ViewBag.Title</h2>

                <div class="form-group row" id="divWallet">
                    <label for="ddlUsrs" class="col-sm-3 col-form-label">User</label>
                    <div class="col-sm-3">
                        <select id="ddlUsrs" class="form-control" data-isRequired="true"
                                data-ctrlType="dropdown" data-objProperty="AuthorId" onchange="loadWalletsData(this, '@Url.Action("GetUserWallet", "Api")', 'tbxWalletId')">
                            <option value="-1">Select user</option>
                            @PageHelpers.GetUsersDto(users, PersonType.NotSpecified)
                        </select>
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>
                <div class="form-group row" id="divWallet">
                    <label for="ddlCreditCardType" class="col-sm-3 col-form-label">Credit card type</label>
                    <div class="col-sm-3">
                        <select id="ddlCreditCardType" class="form-control" data-isRequired="true"
                                data-ctrlType="dropdown" data-objProperty="CardType" disabled="disabled">
                            <option value="-1">Select credit card type</option>
                            @PageHelpers.GetCreditCardTypes()
                        </select>
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>
                <div class="form-group row">
                    <label for="tbxWalletId" class="col-sm-3 col-form-label">Wallet ID</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="tbxWalletId" placeholder=""
                               data-isRequired="true" data-ctrlType="textbox" disabled="disabled"
                               data-objProperty="CreditedWalletId" value="Select user">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="tbxAmount" class="col-sm-3 col-form-label">Amount</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="tbxAmount" placeholder=""
                               data-isRequired="true" data-ctrlType="textbox"
                               data-objProperty="Amount" onkeyup="validateIsDecimal(this)">
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>
                <div class="form-group row">
                    <label for="tbxFees" class="col-sm-3 col-form-label">Fees (%)</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="tbxFees" placeholder=""
                               data-isRequired="true" data-ctrlType="textbox" onkeyup="validateIsPercentage(this)"
                               data-objProperty="Fees">
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>
                <div class="form-group row">
                    <label for="ddlCurrency" class="col-sm-3 col-form-label">Currency</label>
                    <div class="col-sm-3">
                        <select id="ddlCurrency" class="form-control" data-isRequired="true"
                                data-ctrlType="dropdown" data-objProperty="Currency">
                            <option value="-1">Select currency</option>
                            @PageHelpers.GetCurrencies()
                        </select>
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-3">
                        &nbsp;
                    </div>
                    <div class="col-sm-3">
                        <button type="button" class="btn btn-default cutomCtrlWidth" onclick="submitPayin()">Submit payin</button>
                    </div>
                </div>
                <div class="alert alert-info" role="alert">
                    <li>You can use the test card 4970101122334414 with any expiry date in the future and a CVV of 123.</li>
                    <li>Maximum amount of money per transaction by credit card is 1990 GBP.</li>
                </div>
            </div>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        $("#ddlCreditCardType").val("CB_VISA_MASTERCARD");
        
    })
    function submitPayin() {
        if (!validateIsNumber($("#tbxWalletId")[0])) {
            addClassValid($("#tbxWalletId"), false);
            return;
        }
        if (validateFormData('divPayin')) {
            createPayin();
        }
    }
    function createPayin() {
        var allFormCtrls = $("#divPayin").find('[data-objProperty]');

        var jsonData = {};

        allFormCtrls.each(function () {
            var propName = this.getAttribute("data-objProperty");
            jsonData[propName] = $(this).val();
        });

        perfomApiRequest('@Url.Action("CreatePayIn", "Api")', JSON.stringify(jsonData));
    }
</script>

src/MangoPayInegration.Web/Views/Main/Transfers.cshtml
@using MangoPay.SDK.Entities.GET;
@using MangoPayInegration.Controllers;
@using MangoPay.SDK.Core.Enumerations;

@{
    ViewBag.Title = "Transfers";
}
@{ 
    List<UserDTO> users = ApiController.GetAllMangoPayUsers();

<div class="row">
    <div class="card mt-2 form-control">
        <div class="card-body">
            <h2>@ViewBag.Title</h2>

            <div class="form-group row">
                <label for="tbxFirstName" class="col-sm-3 col-form-label">User type</label>
                <div class="form-check form-check-inline ml-3">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" 
                               onchange="toggleUserTypeControls('divNatUserCtrl', 'divLegalUserCtrl', this); setTextboxText('tbxDebitedWalletId', 'Select Author ID')"
                               id="cbxNatUser" value="natural" checked="checked">Natural user
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" 
                               onchange="toggleUserTypeControls('divLegalUserCtrl', 'divNatUserCtrl', this); setTextboxText('tbxDebitedWalletId', 'Select Author ID')"
                               id="cbxLegalUsr" value="legal">Legal user
                    </label>
                </div>
            </div>

            <div class="form-group row" id="divNatUserCtrl">
                <label for="ddlNatUsrs" class="col-sm-3 col-form-label">Debited user ID</label>
                <div class="col-sm-3">
                    <select id="ddlNatUsrs" class="form-control" data-isRequired="true"
                            data-ctrlType="dropdown" onchange="loadWalletsData(this, '@Url.Action("GetUserWallet", "Api")', 'tbxDebitedWalletId')">
                        <option value="-1">Select natural user</option>
                        @PageHelpers.GetUsersDto(users, PersonType.NATURAL)
                    </select>
                </div>
                <label class="text-danger">*</label>
                <div class="invalid-feedback col-sm-4">
                    Required field.
                </div>
            </div>

            <div class="form-group row" id="divLegalUserCtrl" style="display:none">
                <label for="ddlLegalUsrs" class="col-sm-3 col-form-label">Author ID</label>
                <div class="col-sm-3">
                    <select id="ddlLegalUsrs" class="form-control" data-isRequired="true"
                            data-ctrlType="dropdown" onchange="loadWalletsData(this, '@Url.Action("GetUserWallet", "Api")', 'tbxDebitedWalletId')">
                        <option value="-1">Select legal user</option>
                        @PageHelpers.GetUsersDto(users, PersonType.LEGAL)
                    </select>
                </div>
                <label class="text-danger">*</label>
                <div class="invalid-feedback col-sm-4">
                    Required field.
                </div>
            </div>
            <div id="divTransferData">
                <div class="form-group row">
                    <label for="ddlUsrs" class="col-sm-3 col-form-label">Credited user ID</label>
                    <div class="col-sm-3">
                        <select id="ddlUsrs" class="form-control" data-isRequired="true"
                                data-ctrlType="dropdown" onchange="loadWalletsData(this, '@Url.Action("GetUserWallet", "Api")', 'tbxCreditedWalletId')"
                                data-objProperty="CreditedUserId">
                            <option value="-1">Select user</option>
                            @PageHelpers.GetUsersDto(users, PersonType.NotSpecified)
                        </select>
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>
                <div class="form-group row">
                    <label for="ddlTransferCurrency" class="col-sm-3 col-form-label">Transfer currency</label>
                    <div class="col-sm-3">
                        <select id="ddlTransferCurrency" class="form-control" data-isRequired="true"
                                data-ctrlType="dropdown" data-objProperty="Currency">
                            <option value="-1">Select currency</option>
                            @PageHelpers.GetCurrencies()
                        </select>
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>
                <div class="form-group row">
                    <label for="tbxTransferAmount" class="col-sm-3 col-form-label">Transfer amount</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="tbxTransferAmount" placeholder=""
                               data-isRequired="true" data-ctrlType="textbox" data-objProperty="Amount">
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>

                <div class="form-group row">
                    <label for="tbxFeesAmount" class="col-sm-3 col-form-label">Fees (%)</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="tbxFeesAmount" placeholder=""
                               data-isRequired="true" data-ctrlType="textbox" data-objProperty="Fees">
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>

                <div class="form-group row">
                    <label for="tbxDebitedWalletId" class="col-sm-3 col-form-label">Debited wallet ID</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="tbxDebitedWalletId" placeholder=""
                               data-isRequired="true" data-ctrlType="textbox"
                               disabled="disabled" value="Select Author ID"
                               data-objProperty="DebitedWalletId">
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>

                <div class="form-group row">
                    <label for="tbxCreditedWalletId" class="col-sm-3 col-form-label">Credited wallet ID</label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="tbxCreditedWalletId" placeholder=""
                               data-isRequired="true" data-ctrlType="textbox" disabled="disabled" 
                                data-objProperty="CreditedWalletId"
                               value="Select credited user ID">
                    </div>
                    <label class="text-danger">*</label>
                    <div class="invalid-feedback col-sm-4">
                        Required field.
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-3">
                        &nbsp;
                    </div>
                    <div class="col-sm-3">
                        <button type="button" class="btn btn-default cutomCtrlWidth" onclick="submitTransfer()">Submit transfer</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}
    <script>
        function submitTransfer() {
            var errors = 0;
            if (!validateIsNumber($("#tbxCreditedWalletId")[0])) {
                addClassValid($("#tbxCreditedWalletId"), false);
                errors++;
            }
            if (!validateIsNumber($("#tbxDebitedWalletId")[0])) {
                addClassValid($("#tbxDebitedWalletId"), false);
                errors++;
            }

            if (errors == 0) {
                if (validateFormDataWithUserTypeSelection('divTransferData')) {
                    createTransfer();
                }
            }
        }
        function createTransfer() {
            var allFormCtrls = $("#divTransferData").find('[data-objProperty]');

            var jsonData = {};

            allFormCtrls.each(function () {
                var propName = this.getAttribute("data-objProperty");
                jsonData[propName] = $(this).val();
            });
            var authorId = 0;
            if ($("#cbxNatUser").prop("checked")) {
                authorId = $("#ddlNatUsrs").val();
            }
            if ($("#cbxLegalUsr").prop("checked")) {
                authorId = $("#ddlLegalUsrs").val();
            }

            jsonData["AuthorId"] = authorId;

            perfomApiRequest('@Url.Action("CreateTransfer", "Api")', JSON.stringify(jsonData));
        }
    </script>